@startuml

package "Services/Blueprint-Repository" {
    interface "Services/Blueprint-Repository" {

    }
    CLI ()-- "Services/Blueprint-Repository"
    REST ()-- "Services/Blueprint-Repository"
    Web ()-- "Services/Blueprint-Repository"

}


@enduml
