@startuml

package "Services/Raw-Storage" {
    interface "Services/Raw-Storage" {

    }
    CLI ()-- "Services/Raw-Storage"
    REST ()-- "Services/Raw-Storage"
    Web ()-- "Services/Raw-Storage"

}


@enduml
